config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :product_search, only: %i[show] do
    get :search, on: :collection
  end
  resources :product_details, only: %i[show]
  resources :family_details, only: %i[show]
  resources :dashboard, only: %i[index]
  namespace :dashboard do
    resources :groups, except: %i[show destroy]
    resources :families, except: %i[show destroy]
    resources :tax_classifications, except: %i[show destroy]
    resources :products, except: %i[show]
    resources :import_products, only: %i[create]
    resources :export_products, only: %i[create]
    resources :users, except: %i[show]
    resources :lines, except: %i[show destroy]
    resources :subscribers, only: %i[index] do
      collection do
        get :export_csv
      end
    end
  end
  match "/newsletter" => 'home#newsletter', :as => :subscriber, :via => :post
end

app/controllers/dashboard/export_products_controller.rb
module Dashboard
  class ExportProductsController < DashboardController
    def create
      ExportProductsToPdf.execute
      redirect_to dashboard_products_path(pdf: true)
    end
  end
end

app/controllers/dashboard/families_controller.rb
# frozen_string_literal: true

class Dashboard::FamiliesController < DashboardController
  before_action :set_families, only: %i[edit update]

  def index
    if params[:group_id].present?
      render(json: Family.where(group_id: params[:group_id]))
    else
      # FIXME: this should be in a separate action
      @families = Family.order(:family_code).page(params[:page]).per(10)
    end
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.new(families_params)
    if @family.save
      redirect_to dashboard_families_path, notice: "#{@family.family_description} cadastrada com sucesso!"
    else
      flash.now[:alert] = @family.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @family.update(families_params)
      redirect_to dashboard_families_path, notice: "#{@family.family_description} atualizada com sucesso!"
    else
      flash.now[:alert] = @family.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_families
    @family = Family.find(params[:id])
  end

  def families_params
    params.require(:family).permit(:family_code, :family_description, :group_id)
  end
end

app/controllers/dashboard/groups_controller.rb
# frozen_string_literal: true

class Dashboard::GroupsController < DashboardController
  before_action :set_groups, only: %i[edit update]

  def index
    @groups = Group.order(:group_code).page(params[:page]).per(10)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to dashboard_groups_path, notice: "#{@group.group_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @group.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to dashboard_groups_path, notice: "#{@group.group_description} atualizado com sucesso!"
    else
      flash.now[:alert] = @group.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_groups
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:group_code, :group_description, :line_id)
  end
end

app/controllers/dashboard/import_products_controller.rb
module Dashboard
  class ImportProductsController < DashboardController
    def create
      InsertMaterialRecordByCsv.execute(
        import_products_params[:upload]
      )
      redirect_to dashboard_products_path,
        notice: 'Produto(s) cadastrado(s) com sucesso'
    end

    private

    def import_products_params
      params.require(:spreadsheet).permit(:upload)
    end
  end
end

app/controllers/dashboard/lines_controller.rb
# frozen_string_literal: true

class Dashboard::LinesController < DashboardController
  before_action :line, only: %i[edit update]

  def index
    @lines = Line.all
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.new(lines_params)
    if @line.save
      redirect_to dashboard_lines_path, notice: "#{@line.group_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @line.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @line.update
      redirect_to dashboard_lines_path, notice: "#{@line.group_description} atualizado com sucesso!"
    else
      flash.now[:alert] = @line.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def set_lines
    @line = Line.find(params[:id])
  end

  def lines_params
    params.require(:line).permit(:line_description)
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < DashboardController
  before_action :set_products, only: %i[edit update]

  def index
    @products = Product.order(:product_code).page(params[:page]).per(10)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to dashboard_products_path, notice: "#{@product.product_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(products_params)
      redirect_to dashboard_products_path, notice: "#{@product.product_description} atualizado com sucesso!"
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_products
    @product = Product.friendly.find(params[:id])
  end

  def products_params
    params.require(:product).permit(:product_code, :product_description, :product_ean, :product_dun,
      :display_ean, :status, :releases, :family_id, :tax_classification_id, :group_id,
      :status_dimension, :image, similar_products_attributes: [:id, :code, :description, :ean, :dun, :display, :_destroy])
  end
end

app/controllers/dashboard/subscribers_controller.rb
class Dashboard::SubscribersController < DashboardController
  include Exportable
  def index
    @subscribers = Subscriber.order(:email).page(params[:page]).per(10)
  end
end

app/controllers/dashboard/tax_classifications_controller.rb
# frozen_string_literal: true

class Dashboard::TaxClassificationsController < DashboardController
  before_action :set_tax_classification, only: %i[edit update]

  def index
    @tax_classifications = TaxClassification.order(:tax_code).page(params[:page]).per(10)
  end

  def new
    @tax_classification = TaxClassification.new
  end

  def create
    @tax_classification = TaxClassification.new(tax_classifications_params)
    if @tax_classification.save
      redirect_to dashboard_tax_classifications_path, notice: 'Classificação cadastrada com sucesso!'
    else
      flash.now[:alert] = @tax_classification.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @tax_classification.update(tax_classifications_params)
      redirect_to dashboard_tax_classifications_path, notice: 'Classificação alterada com sucesso!'
    else
      flash.now[:alert] = @tax_classification.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_tax_classification
    @tax_classification = TaxClassification.find(params[:id])
  end

  def tax_classifications_params
    params.require(:tax_classification).permit(:tax_code)
  end
end

app/controllers/dashboard/users_controller.rb
# frozen_string_literal: true

class Dashboard::UsersController < DashboardController
  before_action :set_user, only: %i[edit update destroy]
  before_action :allow_without_password, only: [:update]
  def index
    @users = User.order(:username).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to dashboard_users_path, notice: "O usuário #{@user.username} cadastrado com sucesso"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(params_user)
      redirect_to dashboard_users_path, notice: "O usuário #{@user.username} atualizado com sucesso"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to dashboard_users_path, notice: "O usuário #{@user.username} excluido com sucesso"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def params_user
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  # remove o input da validação do devise
  def allow_without_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  def index
    @total_products = Product.count
    @products_releases = Product.releases_true
    @products_status = Product.status_true
  end
end

app/views/dashboard/index.html.erb
<div class="container-fluid">
  <h2 class="text-center">Menu Rápido</h2>
  <hr>
  <div class="row">
    <div class="col-md-3">
      <div class="card bg-primary">
        <div class="card-body text-white text-center">
          <h5 class="card-title">Cadastrar novo produto</h5>
          <hr>
          <p class="card-text"><i class="fas fa-box-open fa-7x"></i></p>
          <%= link_to 'Acessar', new_dashboard_product_path, class:"btn btn-success" %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card bg-primary">
        <div class="card-body text-white text-center">
          <h5 class="card-title">Cadastrar novo grupo</h5>
          <hr>
          <p class="card-text"><i class="fas fa-boxes fa-7x"></i></p>
          <%= link_to 'Acessar', new_dashboard_group_path, class:"btn btn-success" %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card bg-primary">
        <div class="card-body text-white text-center">
          <h5 class="card-title">Cadastrar nova familia</h5>
          <hr>
          <p class="card-text"><i class="fas fa-box-tissue fa-7x"></i></p>
          <%= link_to 'Acessar', new_dashboard_family_path, class:"btn btn-success" %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card bg-primary">
        <div class="card-body text-white text-center">
          <h5 class="card-title">Cadastrar classificação</h5>
          <hr>
          <p class="card-text"><i class="fas fa-barcode fa-7x"></i></p>
          <%= link_to 'Acessar', new_dashboard_tax_classification_path, class:"btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-4">
      <div class="card bg-success">
        <div class="card-body text-white text-center">
          <h5 class="card-title">Produtos cadastrados</h5>
          <hr>
          <p class="card-text count_number"><%= @total_products %> </p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card bg-success">
        <div class="card-body text-white text-center">
          <h5 class="card-title">Produtos Lançamentos</h5>
          <hr>
          <p class="card-text count_number"><%= @products_releases %> </p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card bg-success">
        <div class="card-body text-white text-center">
          <h5 class="card-title">Produtos ativos</h5>
          <hr>
          <p class="card-text count_number"><%= @products_status %> </p>
        </div>
      </div>
    </div>
  </div>
</div>