config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :product_search, only: %i[show] do
    get :search, on: :collection
  end
  resources :product_details, only: %i[show]
  resources :family_details, only: %i[show]
  resources :dashboard, only: %i[index]
  namespace :dashboard do
    resources :groups, except: %i[show destroy]
    resources :families, except: %i[show destroy]
    resources :tax_classifications, except: %i[show destroy]
    resources :products, except: %i[show]
    resources :import_products, only: %i[create]
    resources :export_products, only: %i[create]
    resources :users, except: %i[show]
    resources :lines, except: %i[show destroy]
    resources :subscribers, only: %i[index] do
      collection do
        get :export_csv
      end
    end
  end
  match "/newsletter" => 'home#newsletter', :as => :subscriber, :via => :post
end

app/views/layouts/shared_dashboard/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span class="footer-new">
        Copyright &copy; Catálogo Nestlé <%= Date.current.year %>
        -
        <span class="done_dashboard">
          Desenvolvido por
          <a href="https://www.linkedin.com/in/fabriciobonjorno" target="_blank">Fabricio Bonjorno</a>.
        </span>
      </span>
    </div>
  </div>
</footer>

app/views/layouts/shared_dashboard/_nav.html.erb
        <!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <ul class="navbar-nav ml-auto">
    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <div class="topbar-divider d-none d-sm-block"></div>
    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Bem vindo(a): <%= current_user.username %> </span>
        <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <div class="dropdown-divider"></div>
        <%= link_to destroy_user_session_path, method: :delete, class:"dropdown-item" do %>
          <i class="fa fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp; Logout
        <% end %>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/shared_dashboard/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <!-- Sidebar - Brand -->
  <div class="sidebar-brand-text mx-3"><%= link_to 'Catalogo Nestlé', dashboard_index_path, class:"sidebar-brand d-flex align-items-center justify-content-center" %></div>
  <!-- Divider -->
  <hr class="sidebar-divider my-0">
  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
    <%= link_to dashboard_subscribers_path, class: "nav-link" do %>
      <i class="fas fa-envelope-open-text"></i>
      <span>Newsletter</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to dashboard_groups_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-boxes"></i>
      <span>Grupos</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to dashboard_families_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-box-tissue"></i>
      <span>Familias</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to dashboard_tax_classifications_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-barcode"></i>
      <span>Classificações</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to dashboard_products_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-box-open"></i>
      <span>Produtos</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to dashboard_users_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-user"></i>
      <span>Usúarios</span>
    <% end %>
  </li>
  <hr class="sidebar-divider d-none d-md-block">
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>