config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :product_search, only: %i[show] do
    get :search, on: :collection
  end
  resources :product_details, only: %i[show]
  resources :family_details, only: %i[show]
  resources :dashboard, only: %i[index]
  namespace :dashboard do
    resources :groups, except: %i[show destroy]
    resources :families, except: %i[show destroy]
    resources :tax_classifications, except: %i[show destroy]
    resources :products, except: %i[show]
    resources :import_products, only: %i[create]
    resources :export_products, only: %i[create]
    resources :users, except: %i[show]
    resources :lines, except: %i[show destroy]
    resources :subscribers, only: %i[index] do
      collection do
        get :export_csv
      end
    end
  end
  match "/newsletter" => 'home#newsletter', :as => :subscriber, :via => :post
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include PgSearch::Model
  extend FriendlyId
  validates :product_code, :product_description, :product_ean, :product_dun, :image, presence: true
  validates :product_code, :product_description, uniqueness: true

  belongs_to :family, inverse_of: :products
  belongs_to :group
  belongs_to :tax_classification
  has_many :similar_products, dependent: :destroy
  accepts_nested_attributes_for :similar_products, reject_if: :all_blank, allow_destroy: true

  # belongs_to :parent, class_name: 'Product', optional: true
  # has_many :sub_products, class_name: 'Product', foreign_key: :parent_id, dependent: :destroy

  has_one_attached :image

  friendly_id :product_description, use: :slugged

  pg_search_scope :search,
                  against: %i[product_description product_ean product_code product_dun],
                  associated_against: { similar_products: %i[description code ean dun display] },
                  using: { tsearch: { prefix: true } }

  validate :image_validation

  def image_validation
    if respond_to?(:image) && image.attached?
      if image.blob.byte_size > 2_000_000
        image.purge
        errors[:base] << 'Tamanho maximo 2MB'
      elsif !image.blob.content_type.starts_with?('image/png', 'image/jpeg', 'image/jpg')
        image.purge
        errors[:base] << 'Formato invalido use PNG, JPEG, JPG'
      end
    end
  end

  #scope :only_parents, -> { where(parent_id: nil) }
  scope :releases_home, -> { where(releases: true) }
  scope :status_product, -> { where(status: true) }
  scope :status_dimension, -> { where(status_dimension: true) }
  scope :releases_true, -> { where(releases: true).count }
  scope :status_true, -> { where(status: true).count }
end

app/controllers/dashboard/export_products_controller.rb
module Dashboard
  class ExportProductsController < DashboardController
    def create
      ExportProductsToPdf.execute
      redirect_to dashboard_products_path(pdf: true)
    end
  end
end

app/controllers/dashboard/families_controller.rb
# frozen_string_literal: true

class Dashboard::FamiliesController < DashboardController
  before_action :set_families, only: %i[edit update]

  def index
    if params[:group_id].present?
      render(json: Family.where(group_id: params[:group_id]))
    else
      # FIXME: this should be in a separate action
      @families = Family.order(:family_code).page(params[:page]).per(10)
    end
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.new(families_params)
    if @family.save
      redirect_to dashboard_families_path, notice: "#{@family.family_description} cadastrada com sucesso!"
    else
      flash.now[:alert] = @family.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @family.update(families_params)
      redirect_to dashboard_families_path, notice: "#{@family.family_description} atualizada com sucesso!"
    else
      flash.now[:alert] = @family.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_families
    @family = Family.find(params[:id])
  end

  def families_params
    params.require(:family).permit(:family_code, :family_description, :group_id)
  end
end

app/controllers/dashboard/groups_controller.rb
# frozen_string_literal: true

class Dashboard::GroupsController < DashboardController
  before_action :set_groups, only: %i[edit update]

  def index
    @groups = Group.order(:group_code).page(params[:page]).per(10)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to dashboard_groups_path, notice: "#{@group.group_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @group.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to dashboard_groups_path, notice: "#{@group.group_description} atualizado com sucesso!"
    else
      flash.now[:alert] = @group.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_groups
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:group_code, :group_description, :line_id)
  end
end

app/controllers/dashboard/import_products_controller.rb
module Dashboard
  class ImportProductsController < DashboardController
    def create
      InsertMaterialRecordByCsv.execute(
        import_products_params[:upload]
      )
      redirect_to dashboard_products_path,
        notice: 'Produto(s) cadastrado(s) com sucesso'
    end

    private

    def import_products_params
      params.require(:spreadsheet).permit(:upload)
    end
  end
end

app/controllers/dashboard/lines_controller.rb
# frozen_string_literal: true

class Dashboard::LinesController < DashboardController
  before_action :line, only: %i[edit update]

  def index
    @lines = Line.all
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.new(lines_params)
    if @line.save
      redirect_to dashboard_lines_path, notice: "#{@line.group_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @line.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @line.update
      redirect_to dashboard_lines_path, notice: "#{@line.group_description} atualizado com sucesso!"
    else
      flash.now[:alert] = @line.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def set_lines
    @line = Line.find(params[:id])
  end

  def lines_params
    params.require(:line).permit(:line_description)
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < DashboardController
  before_action :set_products, only: %i[edit update]

  def index
    @products = Product.order(:product_code).page(params[:page]).per(10)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to dashboard_products_path, notice: "#{@product.product_description} cadastrado com sucesso!"
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(products_params)
      redirect_to dashboard_products_path, notice: "#{@product.product_description} atualizado com sucesso!"
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_products
    @product = Product.friendly.find(params[:id])
  end

  def products_params
    params.require(:product).permit(:product_code, :product_description, :product_ean, :product_dun,
      :display_ean, :status, :releases, :family_id, :tax_classification_id, :group_id,
      :status_dimension, :image, similar_products_attributes: [:id, :code, :description, :ean, :dun, :display, :_destroy])
  end
end

app/controllers/dashboard/subscribers_controller.rb
class Dashboard::SubscribersController < DashboardController
  include Exportable
  def index
    @subscribers = Subscriber.order(:email).page(params[:page]).per(10)
  end
end

app/controllers/dashboard/tax_classifications_controller.rb
# frozen_string_literal: true

class Dashboard::TaxClassificationsController < DashboardController
  before_action :set_tax_classification, only: %i[edit update]

  def index
    @tax_classifications = TaxClassification.order(:tax_code).page(params[:page]).per(10)
  end

  def new
    @tax_classification = TaxClassification.new
  end

  def create
    @tax_classification = TaxClassification.new(tax_classifications_params)
    if @tax_classification.save
      redirect_to dashboard_tax_classifications_path, notice: 'Classificação cadastrada com sucesso!'
    else
      flash.now[:alert] = @tax_classification.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @tax_classification.update(tax_classifications_params)
      redirect_to dashboard_tax_classifications_path, notice: 'Classificação alterada com sucesso!'
    else
      flash.now[:alert] = @tax_classification.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_tax_classification
    @tax_classification = TaxClassification.find(params[:id])
  end

  def tax_classifications_params
    params.require(:tax_classification).permit(:tax_code)
  end
end

app/controllers/dashboard/users_controller.rb
# frozen_string_literal: true

class Dashboard::UsersController < DashboardController
  before_action :set_user, only: %i[edit update destroy]
  before_action :allow_without_password, only: [:update]
  def index
    @users = User.order(:username).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to dashboard_users_path, notice: "O usuário #{@user.username} cadastrado com sucesso"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(params_user)
      redirect_to dashboard_users_path, notice: "O usuário #{@user.username} atualizado com sucesso"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to dashboard_users_path, notice: "O usuário #{@user.username} excluido com sucesso"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def params_user
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  # remove o input da validação do devise
  def allow_without_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  def index
    @total_products = Product.count
    @products_releases = Product.releases_true
    @products_status = Product.status_true
  end
end

app/views/dashboard/products/_form_product.html.erb
<%= form_with(model: [:dashboard, @product], local: true, multipart: true) do |f| %>
  <div class="row dynamic">
    <div class="form-group col-md-2">
      <label>Grupo</label>
      <%= collection_select(:product, :group_id, Group.all, :id, :group_description, prompt: "Selecione", class:"form-control") %>
    </div>
    <div class="form-group col-md-2">
      <label>Familia</label>
      <%= collection_select(:product, :family_id, Family.all, :id, :family_description, prompt: "Selecione", class:"form-control") %>
    </div>
    <div class="form-group col-md-2">
      <label>Classificação</label>
      <%= collection_select(:product, :tax_classification_id, TaxClassification.all, :id, :tax_code, prompt: "Selecione", class:"form-control") %>
    </div>
    <div class="form-group col-md-2">
      <%= f.label :product_code %>
      <%= f.text_field :product_code, class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :product_description %>
      <%= f.text_field :product_description, class: "form-control" %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="form-group col-md-3">
      <%= f.label :product_ean %>
      <%= f.text_field :product_ean, class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :display_ean %>
      <%= f.text_field :display_ean, class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :product_dun %>
      <%= f.text_field :product_dun, class: "form-control" %>
    </div>
    <!--<div class="form-group col-md-3">
      <%#= f.label :parent_id, 'Produto Principal' %>
      <%#= f.collection_select :parent_id, Product.only_parents, :id, :product_description, { prompt: 'Selecione' } %>
    </div>-->
    <div class="form-group col-md-3">
      <%= f.label :image, 'Imagem' %>
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="row">
    <div class="form-group ml-2">
      <%= f.label :status, 'Ativo' %>
      <%= f.check_box :status, class: "custom-checkbox" %>
    </div>
    <div class="form-group ml-3">
      <%= f.label :releases, 'Lançamento' %>
      <%= f.check_box :releases, class: "custom-checkbox" %>
    </div>
    <div class="form-group ml-3">
      <%= f.label :status_dimension, 'Horizontal' %>
      <%= f.check_box :status_dimension, class: "custom-checkbox" %>
    </div>
  </div>
  <hr>
  <div class="text-center mt-2"> Códigos similares</div>
  <div id="similar_products">
    <%= f.fields_for :similar_products do |similar_product| %>
      <%= render 'similar_product_fields', f: similar_product %>
    <% end %>
    <%= link_to_add_association 'Adicionar', f, :similar_products, class: "btn btn-success mt-2" %>
  </div>
  <div class="text-center mt-5">
    <%= f.submit class: 'btn btn-success', data: { disable_with: 'Criando... ⌛' } %>
    <%= link_to 'Cancelar', dashboard_products_path, class: "btn btn-danger ml-1" %>
  </div>
<% end %>
<script>
  //document.addEventListener("turbolinks:load", () => {
    $(document).on("turbolinks:load",function(){
      const groupId =  $( "#product_group_id option:selected" ).val();
      if (!groupId) {
        $("#product_family_id option").remove();
        return;
      }
      $.ajax(`/dashboard/families.json?group_id=${groupId}`)
        .done((families) => {
          const htmlOptions = families.reduce((options, family) => {
            options += `<option value='${family.id}'>${family.family_description}</option>`;
            return options;
          }, []);
          $(".dynamic #product_family_id").html(htmlOptions);
        })
        .fail((error) => console.error(error));
  
    //change option
    $("#product_group_id").change(({ target }) => {
      const groupId = target.value;
      if (!groupId) {
        $("#product_family_id option").remove();
        return;
      }
      $.ajax(`/dashboard/families.json?group_id=${groupId}`)
        .done((families) => {
          const htmlOptions = families.reduce((options, family) => {
            options += `<option value='${family.id}'>${family.family_description}</option>`;
            return options;
          }, []);
          $(".dynamic #product_family_id").html(htmlOptions);
        })
        .fail((error) => console.error(error));
    });
  });
</script>

app/views/dashboard/products/_similar_product_fields.html.erb
<div class="nested-fields">
  <div class="row mt-3">
    <div class="col-md-2">
      <%= f.label :code %>
      <%= f.text_field :code, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.label :ean %>
      <%= f.text_field :ean, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.label :dun %>
      <%= f.text_field :dun, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.label :display %>
      <%= f.text_field :display, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <label for="">Remover linha</label>
      <%= link_to_remove_association 'remover', f, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/dashboard/products/edit.html.erb
<div class="container-fluid">
  <h1 class="h3 mb-4 text-gray-800">Editando produto</h1>
  <%= render 'form_product' %>
</div>

app/views/dashboard/products/index.html.erb
<div class="container-fluid">
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Buscar produto" aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>
  <hr>
  <h1 class="h3 mb-4 text-gray-800">Lista de produtos</h1>
  <%= link_to 'Cadastrar', new_dashboard_product_path, class:"btn btn-success mb-2" %>
  <%= form_for :spreadsheet, url: '/dashboard/import_products'  do |f| %>
    <%= f.file_field :upload %>
    <div class="input-groupd">
      <%= button_to 'Importar Planilha', {}, class: "btn btn-primary mb-2", id: :btn_import_spreadsheet %>
      <%= link_to 'Baixar Modelo', '/modelo_produtos.xlsx', download: 'modelo_produtos.xlsx' %>
    </div>
  <% end %>
  <%= form_for :pdf, url: '/dashboard/export_products'  do |f| %>
    <%= button_to 'Exportar Catalogo', {}, class:"btn btn-secondary mb-2" %>
    <%= link_to 'Baixar PDF', '/products.pdf', target: "_blank" if params[:pdf] == 'true' %>
  <% end %>
  <% if @products.empty? %>
    <div class="alert alert-danger" role="alert">
      Nenhum produto cadastrado!
    </div>
  <% else %>
    <div class="table-responsive">
      <table id="products" class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Descrição grupo</th>
            <th scope="col">Descrição familia</th>
            <th scope="col">Código produto</th>
            <th scope="col">Descrição produto</th>
            <th scope="col">Alterar</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <th scope="row"><%= product.id %></th>
              <td><%= product.group.group_description %></td>
              <td><%= product.family.family_description %></td>
              <td><%= product.product_code %></td>
              <td><%= product.product_description %></td>
              <td><%= link_to 'Editar', edit_dashboard_product_path(product), class:"btn btn-secondary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
  <%= paginate @products %>
</div>

<script>
$(document).ready(function() {
    $('#products').DataTable( {
        "paging":   false,
        "ordering": false,
        "info":     false
    } );
} );
</script>

app/views/dashboard/products/new.html.erb
<div class="container-fluid">
  <h1 class="h3 mb-4 text-gray-800">Cadastrando produto</h1>
  <%= render 'form_product' %>
</div>